#!/bin/bash
# Load USSD Gateway Docker image with minimal service impact.
#
# Default: load tar while gateway KEEPS RUNNING. Backs up /opt/ussdgw if present.
# Old Docker images are NEVER removed automatically — use rollback if new release fails.
#
# --switch: backup host + load + recreate gateway on new release tag.
# --fresh-install: stop gateway, remove ALL old images, load (lab reset only).
# --prune --keep N: delete oldest images (default keep=5); never removes running/previous.
# --no-backup: skip /opt/ussdgw tar backup.
# --list-images: show installed release tags + switch history.
set -euo pipefail
source "$(dirname "$0")/env.sh"
# shellcheck source=lib/host-backup.sh
source "$(dirname "$0")/lib/host-backup.sh"

REPO="${DOCKER_IMAGE%%:*}"
MODE="load"
FORCE=0
SKIP_BACKUP=0
PRUNE_KEEP=5

usage() {
    sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'
    exit "${1:-0}"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --load-only|-l) MODE="load" ;;
        --switch|-s) MODE="switch" ;;
        --fresh-install|-f) MODE="fresh" ;;
        --prune|-p) MODE="prune" ;;
        --force) FORCE=1 ;;
        --no-backup) SKIP_BACKUP=1 ;;
        --list-images) MODE="list-images" ;;
        --keep) PRUNE_KEEP="${2:?--keep requires number}"; shift ;;
        -h|--help) usage 0 ;;
        *) echo "Unknown option: $1"; usage 1 ;;
    esac
    shift
done

write_gateway_env() {
    mkdir -p "${GATEWAY_DIR}"
    cat > "${GATEWAY_DIR}/.env" <<EOF
# Generated by 01-load-docker-image.sh — image tag for this package release
USSDGW_IMAGE=${USSDGW_IMAGE}
USSD_VERSION=${USSD_VERSION}
BUILD_ID=${BUILD_ID:-unknown}
EOF
}

maybe_backup_host() {
    local reason="$1"
    if [ "${SKIP_BACKUP}" -eq 1 ]; then
        echo "Skipping host backup (--no-backup)"
        return 0
    fi
    backup_host_ussdgw "${reason}"
}

image_loaded_for_release() {
    docker image inspect "${USSDGW_IMAGE}" >/dev/null 2>&1 || return 1
    if [ -f "${LOADED_IMAGE_STATE}" ] && [ -f "${DOCKER_MANIFEST}" ]; then
        [ "$(tr -d '[:space:]' < "${LOADED_IMAGE_STATE}")" = "${BUILD_ID}" ] && return 0
    fi
    [ ! -f "${DOCKER_MANIFEST}" ] && docker image inspect "${DOCKER_IMAGE}" >/dev/null 2>&1
}

load_image_tar() {
    if [ ! -f "${DOCKER_TAR}" ]; then
        echo "FAIL: missing ${DOCKER_TAR}"
        exit 1
    fi

    if image_loaded_for_release && [ "${FORCE}" -eq 0 ]; then
        echo "Release image already loaded: ${USSDGW_IMAGE}"
        write_gateway_env
        return 0
    fi

    maybe_backup_host "before-docker-load"

    echo "=== Loading Docker image (gateway may stay up) ==="
    echo "  tar:     ${DOCKER_TAR}"
    echo "  release: ${USSDGW_IMAGE}"
    docker load -i "${DOCKER_TAR}"

    if [ "${USSDGW_IMAGE}" != "${DOCKER_IMAGE}" ]; then
        if docker image inspect "${DOCKER_IMAGE}" >/dev/null 2>&1; then
            docker tag "${DOCKER_IMAGE}" "${USSDGW_IMAGE}"
            echo "Tagged release: ${USSDGW_IMAGE}"
        else
            echo "WARN: base image ${DOCKER_IMAGE} not found after load"
            loaded="$(docker images "${REPO}" --format '{{.Repository}}:{{.Tag}}' | head -1)"
            [ -n "${loaded}" ] && docker tag "${loaded}" "${USSDGW_IMAGE}"
        fi
    fi

    [ -n "${BUILD_ID:-}" ] && echo "${BUILD_ID}" > "${LOADED_IMAGE_STATE}"

    write_gateway_env
    echo ""
    list_release_images
    echo ""
    echo "Image ready: ${USSDGW_IMAGE}"
    echo "Old release images kept on disk for rollback."
}

stop_gateway_stack() {
    if [ -f "${PKG_ROOT}/docker-compose.yml" ]; then
        echo "Stopping gateway stack (docker compose down)..."
        (cd "${PKG_ROOT}" && docker compose -f "${PKG_ROOT}/docker-compose.yml" down --remove-orphans) || true
    fi
    for c in "${USSDGW_CONTAINER}" "${USSDGW_INIT_CONTAINER}" \
             ussdgw ussdgw-init ussdgw-prod-release ussdgw-prod-release-init; do
        if docker ps -a --format '{{.Names}}' | grep -qx "${c}"; then
            echo "Removing container: ${c}"
            docker rm -f "${c}" || true
        fi
    done
}

remove_all_repo_images() {
    if docker images -q "${REPO}" 2>/dev/null | grep -q .; then
        echo "Removing images ${REPO}:* ..."
        while IFS= read -r img; do
            [ -n "${img}" ] || continue
            docker rmi -f "${img}" || true
        done < <(docker images "${REPO}" --format '{{.Repository}}:{{.Tag}}')
    fi
}

images_to_keep() {
    local -A keep=()
    keep["${USSDGW_IMAGE}"]=1
    if [ -f "${GATEWAY_DIR}/.env" ]; then
        # shellcheck disable=SC1090
        source "${GATEWAY_DIR}/.env"
        keep["${USSDGW_IMAGE}"]=1
    fi
    if [ -f "${GATEWAY_ENV_PREV}" ]; then
        local prev
        prev="$(grep '^USSDGW_IMAGE=' "${GATEWAY_ENV_PREV}" | cut -d= -f2-)"
        [ -n "${prev}" ] && keep["${prev}"]=1
    fi
    if docker ps --format '{{.Names}}' | grep -qx "${USSDGW_CONTAINER}"; then
        local running_img
        running_img="$(docker inspect -f '{{.Config.Image}}' "${USSDGW_CONTAINER}" 2>/dev/null || true)"
        [ -n "${running_img}" ] && keep["${running_img}"]=1
    fi
    if [ -f "${IMAGE_HISTORY}" ]; then
        while IFS= read -r img; do
            [ -n "${img}" ] && keep["${img}"]=1
        done < <(awk '{print $2, $4}' "${IMAGE_HISTORY}" | tr ' ' '\n' | grep '^restcomm-ussd:')
    fi
    printf '%s\n' "${!keep[@]}"
}

prune_old_images() {
    echo "=== Prune old ${REPO} images (keep last ${PRUNE_KEEP} + running + previous) ==="
    mapfile -t protected < <(images_to_keep)
    mapfile -t all_tags < <(docker images "${REPO}" --format '{{.Repository}}:{{.Tag}}' | sort -r)

    local -A prot_map=()
    local t
    for t in "${protected[@]}"; do prot_map["${t}"]=1; done

    local kept=0 removed=0
    for img in "${all_tags[@]}"; do
        [ -n "${img}" ] || continue
        if [ -n "${prot_map[${img}]+x}" ]; then
            continue
        fi
        if [ "${kept}" -lt "${PRUNE_KEEP}" ]; then
            kept=$((kept + 1))
            continue
        fi
        echo "Removing ${img}"
        docker rmi -f "${img}" 2>/dev/null || true
        removed=$((removed + 1))
    done
    echo "Prune done (removed ${removed}, protected running/previous/history)."
}

case "${MODE}" in
    load)
        load_image_tar
        echo ""
        echo "Gateway NOT restarted. Apply: ./scripts/03-switch-gateway.sh"
        echo "Rollback later:      ./scripts/03-switch-gateway.sh --rollback"
        ;;
    switch)
        maybe_backup_host "before-switch"
        load_image_tar
        exec "$(dirname "$0")/03-switch-gateway.sh"
        ;;
    fresh)
        echo "=== Fresh install: stop gateway, remove ALL images, load ==="
        stop_gateway_stack
        remove_all_repo_images
        FORCE=1 load_image_tar
        echo "Done. Start: ./scripts/03-start-gateway.sh"
        ;;
    prune)
        prune_old_images
        ;;
    list-images)
        list_release_images
        ;;
esac
